name: CI

on:
  push:
  pull_request:

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    concurrency: ci-nodejs-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
